version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000" # Expose the backend to the host machine
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose only the frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    depends_on:
      - backend # Frontend depends on the backend

networks:
  app-network:
    driver: bridge
