const ROLES = Object.freeze({
  ADMIN: 'ROLE_ADMIN',
  ORGANIZER_ADMIN: 'ROLE_ORGANIZER_ADMIN',
  ORGANIZER: 'ROLE_ORGANIZER',
  PARTICIPANT: 'ROLE_PARTICIPANT',
});

const PUBLIC_REGISTRATION_ROLES = new Set([
  ROLES.ORGANIZER,
  ROLES.PARTICIPANT,
]);

module.exports = { ROLES, PUBLIC_REGISTRATION_ROLES };
