name : CI/CD pipeline

on:
  push: 
    branches:
    - main
    - feature/setup_github_actions
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Move directory   
        run: cd backend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12
      - name: Install dependencies 
        run: | 
          cd backend
          npm install -g pnpm
      - name: Install pnpm dependencies
        run: | 
          cd backend
          pnpm install
      - name: Run linter
        run: | 
          cd backend
          pnpm run lint
      #- name: Run tests
      #  run: pnpm test
