name : CI/CD pipeline

on:
  push: 
    branches:
    - main
    - feature/setup_github_actions
  pull_request:
    branches:
    - main
env:
  Backend_dir: /home/runner/work/Festivio/Festivio/backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: dir
        run: echo `pwd`
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Move directory   
        run: cd ${{ env.Backend_dir }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12
      - name: Install dependencies 
        run: | 
          cd ${{ env.Backend_dir }}
          npm install -g pnpm
      - name: Install pnpm dependencies
        run: | 
          cd ${{ env.Backend_dir }}
          pnpm install
      - name: Run linter
        run: | 
          cd ${{ env.Backend_dir }}
          pnpm run lint
      #- name: Run tests
      #  run: pnpm test
