name : Workflow backend

on:
  push: 
    branches:
    - master
    - develop
    - feature/tests
  pull_request:
    branches:
    - master
    - develop
env:
  Backend_dir: /home/runner/work/Festivio/Festivio/backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: dir
        run: echo `pwd`
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Move directory   
        run: cd ${{ env.Backend_dir }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12
      - name: Install dependencies 
        run: | 
          cd ${{ env.Backend_dir }}
          npm install
      - name: Lint with ESLint
        run: |
          cd ${{ env.Backend_dir }}
          npm run lint
      - name: Format with Prettier
        run: |
          cd ${{ env.Backend_dir }}
          npm run format
      - name: Run tests
        run: |
          cd ${{ env.Backend_dir }}
          npm run test
